# Generated by Django 4.0.3 on 2022-04-05 23:35

from django.db import migrations

def create_through_relations(apps, schema_editor):
    Order = apps.get_model('starInventory', 'Order')
    OrderProduct = apps.get_model('starInventory', 'OrderProduct')
    for order in Order.objects.all():
        for product in order.product.all():
            OrderProduct(
                product=product,
                order=order,
                quantity=1
            ).save()



class Migration(migrations.Migration):

    dependencies = [
        ('starInventory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
