# Generated by Django 4.0.3 on 2022-04-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starInventory', '0002_auto_20220406_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
