# Generated by Django 4.0.3 on 2022-04-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starInventory', '0003_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='starInventory.CustomerOrder', to='starInventory.product'),
        ),
    ]
