# Generated by Django 4.0.3 on 2022-04-05 22:48

from django.db import migrations

def create_through_relations(apps, schema_editor):
    Product = apps.get_model('starInventory', 'Product')
    ProductPart = apps.get_model('starInventory', 'ProductPart')
    for product in Product.objects.all():
        for part in product.part.all():
            ProductPart(
                product=product,
                part=part,
                quantity=1
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('starInventory', '0004_order_product'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
