# Generated by Django 4.0.3 on 2022-04-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starInventory', '0006_remove_product_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part',
            field=models.ManyToManyField(through='starInventory.ProductPart', to='starInventory.part'),
        ),
    ]
